### PR TITLE
Error if generating bindings for non-existent component

### LINKED ISSUE #13: Providing a non-existing component id to `spin deps generate-bindings` fails silently
Using wrong component Id:

```shell
> spin deps generate-bindings -L rust -o challenge1/src/bindings -c challenge-1`

```
Nothing is printed in the terminal as the command completes, an error message would be good to have.

Using the right component Id:

```shell
> spin deps generate-bindings -L rust -o challenge1/src/bindings -c challenge1
Bindings generated for Rust in challenge1/src/bindings...
```

Confirmation that bindings are generated.

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #13.

```
$ spin deps generate-bindings -L rust -o bindywoo -c nonexistentcomp
Error: The WIT file that `spin deps` uses to track component dependencies doesn't exist. This can happen if:
* the component name is incorrect
* you've not previously run `spin deps add` for this component
The expected file is ".wit/components/nonexistentcomp/deps.wit"
```

### CODE REVIEW

**Review by fibonacci1729 — APPROVED** [review]

File: src/commands/bindings.rs [hunk 1]
```diff
@@ -34,8 +34,12 @@ impl GenerateBindingsCommand {
             .join(SPIN_DEPS_WIT_FILE_NAME);
 
         if !std::fs::exists(&wit_path)? {
-            // TODO: warn that the file does not exist
```
Comment (mikkelhegn) [inline src/commands/bindings.rs:37]: LOL!
